using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace ProjectBootstrap.Editor
{
    /// <summary>
    /// Handles creation of supporting files (.gitkeep, README, warnings)
    /// </summary>
    public static class FileGenerator
    {
        /// <summary>
        /// Creates an empty .gitkeep file to ensure Git tracks empty folders
        /// </summary>
        /// <param name="folderPath">Path to the folder where .gitkeep should be created</param>
        public static void CreateGitKeepFile(string folderPath)
        {
            string filePath = Path.Combine(folderPath, ".gitkeep").Replace("\\", "/");

            if (File.Exists(filePath))
                return;

            try
            {
                File.WriteAllText(filePath, "");
                AssetDatabase.ImportAsset(filePath);
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[Folder Generator] Failed to create .gitkeep: {filePath}\n{e.Message}");
            }
        }

        /// <summary>
        /// Creates a helper text file with .gitignore instructions
        /// </summary>
        /// <param name="folderPath">Path to the folder where the helper file should be created</param>
        public static void CreateGitignoreHelper(string folderPath)
        {
            string filePath = Path.Combine(folderPath, "ADD_TO_GITIGNORE.txt").Replace("\\", "/");

            if (File.Exists(filePath))
            {
                Debug.LogWarning($"[Folder Generator] Gitignore helper already exists: {filePath}");
                return;
            }

            string relativePath = folderPath.Replace("\\", "/");
            string content = string.Format(FolderStructureData.GitignoreHelperTemplate, relativePath);

            try
            {
                File.WriteAllText(filePath, content);
                AssetDatabase.ImportAsset(filePath);
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[Folder Generator] Failed to create gitignore helper: {filePath}\n{e.Message}");
            }
        }

        /// <summary>
        /// Creates a warning file explaining the performance implications of the Resources folder
        /// </summary>
        /// <param name="folderPath">Path to the Resources folder</param>
        public static void CreateResourcesWarning(string folderPath)
        {
            string filePath = Path.Combine(folderPath, "README_RESOURCES_WARNING.txt").Replace("\\", "/");

            if (File.Exists(filePath))
                return;

            try
            {
                File.WriteAllText(filePath, FolderStructureData.ResourcesWarning);
                AssetDatabase.ImportAsset(filePath);
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[Folder Generator] Failed to create Resources warning: {filePath}\n{e.Message}");
            }
        }

        /// <summary>
        /// Creates a README.md file with folder description and purpose
        /// </summary>
        /// <param name="folderPath">Path where the README should be created</param>
        /// <param name="folderName">Name of the folder (used as title)</param>
        /// <param name="description">Description content for the README</param>
        public static void CreateReadme(string folderPath, string folderName, string description)
        {
            string filePath = Path.Combine(folderPath, "README.md").Replace("\\", "/");

            if (File.Exists(filePath))
                return;

            string content = $@"# {folderName}

{description}

---
*This file was auto-generated by Project Bootstrap*
";

            try
            {
                File.WriteAllText(filePath, content);
                AssetDatabase.ImportAsset(filePath);
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[Folder Generator] Failed to create README: {filePath}\n{e.Message}");
            }
        }
    }
}
